name: pushing docker image 4
on: workflow_dispatch
jobs:
  java4:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
         image: sai340/python/imagepython
         registry: docker.io
         username: sai340
         password: Saikiran@340
